# Generated by Django 3.0.5 on 2020-06-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_starter_app', '0002_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='10000', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.EmailField(default='6-26-2020', max_length=254),
            preserve_default=False,
        ),
    ]
